<a href="https://colab.research.google.com/github/carolvieirav/Labs/blob/master/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [0]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [5]:
# your code here
np.__version__

'1.17.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [10]:
# Method 1 
a= np.random.random((2,3,5))

[array([[[0.90945954, 0.5749582 , 0.81691596, 0.12945464, 0.37676355],
         [0.99018882, 0.12395717, 0.67153331, 0.52918566, 0.67512204],
         [0.20101671, 0.47660514, 0.48063388, 0.94167482, 0.95113593]],
 
        [[0.74957647, 0.49011444, 0.51261298, 0.56725894, 0.19880707],
         [0.5483454 , 0.49115247, 0.57094557, 0.69678297, 0.75389902],
         [0.09237059, 0.81740585, 0.7172741 , 0.55188813, 0.48924165]]])]

In [0]:
# Method 2

In [0]:
# Method 3

#### 4. Print *a*.


In [0]:
# your code here
print(np.array(a))

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [0]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [25]:
# your code here
print(np.array(b))

[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [36]:
# your code here
if np.array(a).shape is np.array(b).shape:
  print("It's a match!")
else:
  print("They have diferent sizes!")

They have diferent sizes!


#### 8. Are you able to add *a* and *b*? Why or why not?


In [35]:
# your answer here
a + b
print('No, It needs to be in the same structure!')

No, It needs to be in the same structure!


#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the reshaped array to variable *c*.

In [0]:
# your code here
c = b.reshape((2,3,5))

In [56]:
c.shape

(2, 3, 5)

In [0]:
?np.reshape

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [45]:
# your code/answer here
d = a+c
print('Now it has the same structure!')

Now it has the same structure!


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [66]:
# your code/answer here
print(a)
print(d)
print("The diferance is the permutation of the arrays with 'c' and the relation between the two is that all values are type float!")

[array([[[0.90945954, 0.5749582 , 0.81691596, 0.12945464, 0.37676355],
        [0.99018882, 0.12395717, 0.67153331, 0.52918566, 0.67512204],
        [0.20101671, 0.47660514, 0.48063388, 0.94167482, 0.95113593]],

       [[0.74957647, 0.49011444, 0.51261298, 0.56725894, 0.19880707],
        [0.5483454 , 0.49115247, 0.57094557, 0.69678297, 0.75389902],
        [0.09237059, 0.81740585, 0.7172741 , 0.55188813, 0.48924165]]])]
[[[[1.90945954 1.5749582  1.81691596 1.12945464 1.37676355]
   [1.99018882 1.12395717 1.67153331 1.52918566 1.67512204]
   [1.20101671 1.47660514 1.48063388 1.94167482 1.95113593]]

  [[1.74957647 1.49011444 1.51261298 1.56725894 1.19880707]
   [1.5483454  1.49115247 1.57094557 1.69678297 1.75389902]
   [1.09237059 1.81740585 1.7172741  1.55188813 1.48924165]]]]
The diferance is the permutation of the arrays with 'c' and the relation between the two is that all values are type float!


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [0]:
# your code here
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [70]:
# your code/answer here
e is a
print("They are not equal because the permutation with 'c' infers diferent values")

They are not equal because of the state of the permutation with 'c'


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [0]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [0]:
# your code here

f = np.empty((2,3,6))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [0]:
# your code here

f[item > d_min & item < d_mean] = 25
f[item > d_mean & item < d_max] = 75
f[item == d_mean] = 50
f[item == d_min] = 0
f[item == d_max] = 100
 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])



#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [0]:
# your code here
print(d)
print(f)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [0]:
# your code here